- name: Check if a custom config if defined
  delegate_to: localhost
  become: false
  ansible.builtin.stat:
    path: "{{ (bind_config_file if bind_config_file.startswith('/') else
      playbook_dir + '/' + bind_config_file) }}"
  register: config
  when: bind_config_file is defined

- name: Check if a custom zone files directory is defined
  delegate_to: localhost
  become: false
  ansible.builtin.stat:
    path: "{{ (bind_zones_dir if bind_zones_dir.startswith('/') else
      playbook_dir + '/' + bind_zones_dir) }}"
  register: zones_dir
  when: bind_zones_dir is defined

- name: Set configuration flags
  ansible.builtin.set_fact:
    use_config_file: "{{ config.stat.exists | default(false) }}"
    use_custom_zones: "{{ zones_dir.stat.exists | default(false) }}"

- name: Add custom named.conf
  ansible.builtin.copy:
    src: "{{ config.stat.path }}"
    dest: /etc/named.conf
    mode: "0640"
    backup: true
  register: named_conf
  when: use_config_file

- name: Add default named.conf
  ansible.builtin.copy:
    src: "{{ ansible_os_family }}.conf"
    dest: /etc/named.conf
    mode: "0640"
    backup: true
  when: not use_config_file
  notify: Restart Bind service

- name: Ensure zone files directory exists
  ansible.builtin.file:
    path: "{{ bind_zones_path }}"
    state: directory
    mode: "0770"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
  when: use_custom_zones

- name: Add zone files
  ansible.builtin.copy:
    src: "{{ zones_dir.stat.path }}"
    dest: "{{ bind_zones_path }}/"
    mode: "0640"
    owner: root
    group: "{{ bind_group }}"
    backup: true
  when: use_custom_zones
  notify: Restart Bind service
