- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        - default.yaml
      paths: "vars"

- name: Install Bind
  ansible.builtin.package:
    name: "{{ bind_package_name }}"
    state: present

- name: Configure Bind
  ansible.builtin.include_tasks: configure.yaml

- name: Validate config
  ansible.builtin.include_tasks: validate.yaml

- name: Open up firewall
  ansible.builtin.include_tasks: firewall.yaml

- name: Resolve any conflicting ports
  ansible.builtin.include_tasks: resolve-port-conflict.yaml

- name: Start Bind
  ansible.builtin.include_tasks: start-service.yaml
